### ISSUE TITLE
error instantiating handler for prefix "/sync-to-googlecloudstorage/", type "sync": Error reading sync queue to memory: Error, off: 0x3737336633643c0, EOF

### ISSUE THREAD

**Issue by mkorenkov** [mkorenkov/docker-perkeep#12]
```
2016/07/01 02:33:59 Starting camlistored version 2016-06-23-ce8b329+; Go go1.6 (linux/amd64)
2016/07/01 02:33:59 Starting to listen on http://localhost:3179
2016/07/01 02:33:59 Slurping corpus to memory from index...
2016/07/01 02:33:59 Slurping corpus to memory from index... (1/9: meta rows)
2016/07/01 02:34:23 Scanned prefix "meta": 451618 rows, 23.400909983s
2016/07/01 02:34:23 Slurping corpus to memory from index... (2/9: prefix "signerkeyid")
2016/07/01 02:34:23 Slurping corpus to memory from index... (3/9: prefix "claim")
2016/07/01 02:34:23 Slurping corpus to memory from index... (4/9: prefix "fileinfo")
2016/07/01 02:34:23 Slurping corpus to memory from index... (5/9: prefix "filetimes")
2016/07/01 02:34:23 Slurping corpus to memory from index... (6/9: prefix "imagesize")
2016/07/01 02:34:23 Slurping corpus to memory from index... (7/9: prefix "wholetofile")
2016/07/01 02:34:23 Slurping corpus to memory from index... (8/9: prefix "exifgps")
2016/07/01 02:34:23 Slurping corpus to memory from index... (9/9: prefix "mediatag")
2016/07/01 02:34:23 Scanned prefix "signerkeyid": 1 rows, 3.002144ms
2016/07/01 02:34:23 Scanned prefix "mediatag": 0 rows, 24.589028ms
2016/07/01 02:34:24 Scanned prefix "claim": 41865 rows, 1.283925078s
2016/07/01 02:34:25 Scanned prefix "wholetofile": 9905 rows, 1.875097396s
2016/07/01 02:34:25 Scanned prefix "fileinfo": 10072 rows, 2.370425575s
2016/07/01 02:34:25 Scanned prefix "imagesize": 9763 rows, 2.63734108s
2016/07/01 02:34:26 Scanned prefix "filetimes": 9905 rows, 2.931046605s
2016/07/01 02:34:26 Scanned prefix "exifgps": 298 rows, 2.940399211s
2016/07/01 02:34:26 Corpus stats: 113.708 MiB mem: 451618 blobs (23.170 GiB) (131720 schema (8553 permanode, 10072 file (9763 image), ...)
2016/07/01 02:34:26 Corpus scanning CPU usage: 1.25s
2016/07/01 02:34:27 [SyncHandler /bs/ -> /index/] Added 0 pending blobs from sync queue to pending list
2016/07/01 02:34:27 [SyncHandler /bs/ -> /sto-googlecloudstorage/] Added 0 pending blobs from sync queue to pending list
2016/07/01 02:34:27 Caught panic installer handlers: error instantiating handler for prefix "/sync-to-googlecloudstorage/", type "sync": Error reading sync queue to memory: Error, off: 0x3737336633643c0, EOF
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
    /usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
    /usr/local/go/src/runtime/debug/stack.go:16 +0x18
camlistore.org/pkg/serverinit.(*Config).InstallHandlers.func1(0xc820835b60)
    /opt/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:514 +0xd7
panic(0xe2ba00, 0xc82b4123e0)
    /usr/local/go/src/runtime/panic.go:426 +0x4e9
camlistore.org/pkg/serverinit.(*handlerLoader).setupHandler.func1(0xc820205e30, 0xc8208ea600, 0x12cef80, 0x1c)
    /opt/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:307 +0x265
panic(0xe2ba00, 0xc82b4123e0)
    /usr/local/go/src/runtime/panic.go:426 +0x4e9
camlistore.org/pkg/serverinit.exitFailure(0xc82b20d000, 0x37, 0xc820835640, 0x3, 0x3)
    /opt/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:276 +0x199
camlistore.org/pkg/serverinit.(*handlerLoader).setupHandler(0xc8208ea600, 0x12cef80, 0x1c)
    /opt/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:357 +0x1eca
camlistore.org/pkg/serverinit.(*handlerLoader).setupAll(0xc8208ea600)
    /opt/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:230 +0x9e
camlistore.org/pkg/serverinit.(*Config).InstallHandlers(0xc820208300, 0x7f2948391f10, 0xc8208ea500, 0xc82020e040, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /opt/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/pkg/serverinit/serverinit.go:580 +0xcfb
main.Main(0x0, 0x0)
    /opt/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/server/camlistored/camlistored.go:422 +0xea5
main.main()
    /opt/camlistore/tmp/build-gopath-nosqlite/src/camlistore.org/server/camlistored/camlistored.go:355 +0x29
Error parsing config: Caught panic: error instantiating handler for prefix "/sync-to-googlecloudstorage/", type "sync": Error reading sync queue to memory: Error, off: 0x3737336633643c0, EOF
```

**Comment by mkorenkov** [comment]
it seems, that's jut an issue with the simple config, never had this one on the servers with verbose config.

**Comment by mkorenkov** [comment]
closing old issue
